OPENQASM 2.0;
include "qelib1.inc";
qreg cin[1];
qreg a[1];
qreg b[1];
qreg cout[1];
creg meas[4];
csx b[0],cout[0];
cx a[0],b[0];
sdg b[0];
z cout[0];
csx b[0],cout[0];
cx a[0],b[0];
z cout[0];
csx a[0],cout[0];
cx a[0],b[0];
csx b[0],cout[0];
cx cin[0],b[0];
sdg b[0];
z cout[0];
csx b[0],cout[0];
cx cin[0],b[0];
z cout[0];
csx cin[0],cout[0];
cx cin[0],b[0];
barrier cin[0],a[0],b[0],cout[0];
measure cin[0] -> meas[0];
measure a[0] -> meas[1];
measure b[0] -> meas[2];
measure cout[0] -> meas[3];
